# Generated by Django 4.2 on 2025-03-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="administrador",
            old_name="fecha_registro",
            new_name="date_joined",
        ),
        migrations.AddField(
            model_name="administrador",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="administrador",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="administrador",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="administrador",
            name="celular",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="administrador",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
