# Generated by Django 4.2 on 2025-03-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrador",
            "0002_rename_fecha_registro_administrador_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="administrador", name="date_joined",),
        migrations.RemoveField(model_name="administrador", name="is_active",),
        migrations.RemoveField(model_name="administrador", name="is_staff",),
        migrations.AlterField(
            model_name="administrador",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="administrador",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
