# Generated by Django 4.2 on 2025-03-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0003_remove_administrador_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="administrador", name="email",),
        migrations.AddField(
            model_name="administrador",
            name="username",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="administrador",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
