# Generated by Django 4.2 on 2025-03-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrador",
            "0004_remove_administrador_email_administrador_username_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="administrador", name="username",),
        migrations.AlterField(
            model_name="administrador",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
