# Generated by Django 4.2 on 2025-03-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0005_remove_administrador_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrador",
            name="email",
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
