# Generated by Django 4.2 on 2025-03-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0006_administrador_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="administrador", name="email",),
        migrations.AddField(
            model_name="administrador",
            name="username",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
