# Generated by Django 4.2 on 2025-03-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0007_remove_administrador_email_administrador_username"),
    ]

    operations = [
        migrations.DeleteModel(name="Administrador",),
    ]
