# Generated by Django 4.2 on 2025-03-12 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registro", "0003_registro_validado_alter_registro_celular_and_more"),
        ("administrador", "0008_delete_administrador"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entrada", models.DateTimeField(blank=True, null=True)),
                ("salida", models.DateTimeField(blank=True, null=True)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registro.registro",
                    ),
                ),
            ],
            options={"unique_together": {("usuario", "fecha")},},
        ),
    ]
