# Generated by Django 4.2 on 2025-03-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0009_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistencia",
            name="entrada",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="salida",
            field=models.DateField(blank=True, null=True),
        ),
    ]
