# Generated by Django 4.2 on 2025-03-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0010_alter_asistencia_entrada_alter_asistencia_salida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistencia",
            name="entrada",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="salida",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
