# Generated by Django 4.2 on 2025-02-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(blank=True, max_length=8, null=True)),
                ("nombres", models.CharField(max_length=100)),
                ("apellido_paterno", models.CharField(max_length=100)),
                ("apellido_materno", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("celular", models.CharField(blank=True, max_length=15, null=True)),
                ("proyecto_investigacion", models.FileField(upload_to="pdfs/")),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "registro",},
        ),
    ]
