# Generated by Django 4.2 on 2025-02-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="proyecto_investigacion",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AlterModelTable(name="registro", table=None,),
    ]
