# Generated by Django 4.2.20 on 2025-03-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0003_registro_validado_alter_registro_celular_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="proyecto_investigacion",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
