# Generated by Django 4.2.20 on 2025-03-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0004_alter_registro_proyecto_investigacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="celular",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="registro",
            name="dni",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="registro",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
