# Generated by Django 4.2.20 on 2025-04-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0005_alter_registro_celular_alter_registro_dni_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registro",
            old_name="proyecto_investigacion",
            new_name="voucher_pago",
        ),
        migrations.AddField(
            model_name="registro",
            name="doc_acreditivo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registro",
            name="entidad_procedencia",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registro",
            name="pais",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registro",
            name="tipo_participante",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registro",
            name="dni",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
