# Generated by Django 4.2.20 on 2025-04-06 04:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "registro",
            "0006_rename_proyecto_investigacion_registro_voucher_pago_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="registro",
            name="monto",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="registro",
            name="doc_acreditivo",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="registro",
            name="pais",
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name="registro",
            name="tipo_participante",
            field=models.CharField(
                choices=[
                    ("", "(Seleccione)"),
                    ("estudiante (solo pregrado)", "Estudiante (solo pregrado)"),
                    ("participante", "Participante"),
                ],
                default="Seleccione",
                max_length=50,
            ),
        ),
    ]
