# Generated by Django 4.2.20 on 2025-04-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0010_alter_registro_monto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="monto",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
