# Generated by Django 4.2.20 on 2025-04-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_alter_registro_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo_participante',
            field=models.CharField(choices=[('', '(Seleccione)'), ('estudiante (pregrado)', 'Estudiante (pregrado)'), ('participante', 'Participante')], default='Seleccione', max_length=50),
        ),
    ]
