# Generated by Django 4.2.20 on 2025-07-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_alter_registro_voucher_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='operacion_pago',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
