# Generated by Django 4.2.20 on 2025-07-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_alter_registro_operacion_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='operacion_pago',
            field=models.CharField(default=11111, max_length=15),
        ),
    ]
